# Generated by Django 5.1.3 on 2024-11-26 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bewertung_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voting',
            name='product',
        ),
        migrations.RemoveField(
            model_name='voting',
            name='user',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Voting',
        ),
    ]
