# Generated by Django 5.1.3 on 2024-11-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bewertung_app', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='stars',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
